In [34]:
import pandas as pd


## 1. 데이터준비

In [7]:
df=pd.read_csv('./tmdb_5000_movies.csv')
df.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [8]:
df.shape

(4803, 20)

## 2. 데이터 전처리

In [20]:
data=df[['id','genres','vote_average','vote_count','popularity','title','keywords','overview']]
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [21]:
data.shape

(4803, 8)

In [22]:
# 500위 정도에 들어오려면? vote_count가 상위 몇퍼?
m=data['vote_count'].quantile(0.9)
print(m)
data=data.loc[data['vote_count'] >= m]

1838.4000000000015


In [24]:
data.shape

(481, 8)

In [25]:
c=data['vote_average'].mean()
print(c)

6.962993762993763


In [26]:
def weight_rating(x,m=m,c=c):
    v=x['vote_count']
    r=x['vote_average']
    
    return ( v / (v+m) * r ) + ( m / (v+m) * c )

In [27]:
data['score'] = data.apply(weight_rating,axis=1)

In [28]:
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

In [29]:
data.shape

(481, 9)

In [30]:
data[['genres','keywords']].head()

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [37]:
import ast as ast

In [35]:
data['genres'] = data['genres'].apply(ast.literal_eval)
data['keywords'] = data['keywords'].apply(ast.literal_eval)

In [36]:
data[['genres','keywords']].head()

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
3  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   
4  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                            keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id':...  
1  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...  
2  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...  
3  [{'id': 849, 'name': 'dc comics'}, {'id': 853,...  
4  [{'id': 818, 'name': 'based on novel'}, {'id':...

In [39]:
data['genres'] = data['genres'].apply(lambda x:[d['name'] for d in x]).apply(lambda x:" ".join(x))
data['keywords'] = data['keywords'].apply(lambda x:[d['name'] for d in x]).apply(lambda x:" ".join(x))

In [40]:
data.head()

id                                    genres  vote_average  vote_count  \
0   19995  Action Adventure Fantasy Science Fiction           7.2       11800   
1     285                  Adventure Fantasy Action           6.9        4500   
2  206647                    Action Adventure Crime           6.3        4466   
3   49026               Action Crime Drama Thriller           7.6        9106   
4   49529          Action Adventure Science Fiction           6.1        2124   

   popularity                                     title  \
0  150.437577                                    Avatar   
1  139.082615  Pirates of the Caribbean: At World's End   
2  107.376788                                   Spectre   
3  112.312950                     The Dark Knight Rises   
4   43.926995                               John Carter   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   
2  spy based on novel secret agent sequel mi6 bri...   
3  dc comics crime fighter terrorist secret ident...   
4  based on novel mars medallion space travel pri...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

## 3.콘텐츠기반 필터링

In [42]:
data.genres.head(2)

0    Action Adventure Fantasy Science Fiction
1                    Adventure Fantasy Action
Name: genres, dtype: object

In [45]:
 pip install sklearn

  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Using cached scikit_learn-0.24.2-cp38-cp38-win_amd64.whl (6.9 MB)
  Using cached threadpoolctl-2.2.0-py3-none-any.whl (12 kB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)Note: you may need to restart the kernel to use updated packages.

Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.

You should consider upgrading via the 'c:\users\gg664\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.



    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


## 장르 벡터화

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
counter_vector = CountVectorizer(ngram_range=(1,3))

In [55]:
c_vector_genres = counter_vector.fit_transform(data['genres'])

In [56]:
c_vector_genres.shape

(481, 364)

In [57]:
c_vector_genres

<481x364 sparse matrix of type '<class 'numpy.int64'>'
	with 3238 stored elements in Compressed Sparse Row format>

## 유사도값 (코사인 유사도)

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_genre = cosine_similarity(c_vector_genres, c_vector_genres).argsort()[:,::-1]
print(similarity_genre)

[[  0  13  42 ... 298 297 240]
 [ 11   1 200 ... 329 330 240]
 [  2 376 216 ... 314 304 240]
 ...
 [478 187  12 ... 326 327   0]
 [479 466 383 ... 220 224   0]
 [480 468 294 ... 246 248   0]]


In [60]:
similarity_genre.shape

(481, 481)

In [66]:
def recommend_movie_list(df,movie_title,top=30):
    #특정 영화정보 뽑아내기
    target_movie_index = df[df['title'] == movie_title].index.values
    
    # 타겟영화와 비슷한 코사인유사도값
    sim_index = similarity_genre[target_movie_index,:top].reshape(-1)
    #본인제외
    sim_index = sim_index[sim_index!=target_movie_index]
    
    #추천결과 새로운 df생성, 평균평점(score)으로 정렬
    result = df.iloc[sim_index].sort_values('score',ascending=False)[:10]
    
    return result
    

In [68]:
recommend_movie_list(data,movie_title='Avatar')

id                                    genres  vote_average  \
85   100402          Action Adventure Science Fiction           7.6   
46   127585  Action Adventure Fantasy Science Fiction           7.5   
47    54138          Action Adventure Science Fiction           7.4   
19   122917                  Action Adventure Fantasy           7.1   
182  102899          Science Fiction Action Adventure           7.0   
426   70160         Science Fiction Adventure Fantasy           6.9   
126   76338                  Action Adventure Fantasy           6.8   
31    68721          Action Adventure Science Fiction           6.8   
507     602          Action Adventure Science Fiction           6.7   
30      558                  Action Adventure Fantasy           6.7   

     vote_count  popularity                                      title  \
85         5764   72.225265        Captain America: The Winter Soldier   
46         6032  118.078691                 X-Men: Days of Future Past   
47         4418   78.291018                    Star Trek Into Darkness   
19         4760  120.965743  The Hobbit: The Battle of the Five Armies   
182        5880  120.093610                                    Ant-Man   
426        9455   68.550698                           The Hunger Games   
126        4755   99.499595                       Thor: The Dark World   
31         8806   77.682080                                 Iron Man 3   
507        3260   60.442593                           Independence Day   
30         4321   35.149586                               Spider-Man 2   

                                              keywords  \
85   washington d.c. future shield marvel comic sup...   
46   1970s mutant time travel marvel comic based on...   
47   spacecraft friendship sequel futuristic space ...   
19   corruption elves dwarves orcs middle-earth (to...   
182  marvel comic superhero based on comic book aft...   
426  hallucination dystopia female protagonist bow ...   
126  marvel comic superhero based on comic book hos...   
31   terrorist war on terror tennessee malibu marve...   
507  spacecraft patriotism countdown independence i...   
30   dual identity love of one's life pizza boy mar...   

                                              overview     score  
85   After the cataclysmic events in New York with ...  7.445960  
46   The ultimate X-Men ensemble fights a war for t...  7.374564  
47   When the crew of the Enterprise is called back...  7.271589  
19   Immediately after the events of The Desolation...  7.061828  
182  Armed with the astonishing ability to shrink i...  6.991186  
426  Every year in the ruins of what was once North...  6.910254  
126  Thor fights to restore order across the cosmos...  6.845447  
31   When Tony Stark's world is torn apart by a for...  6.828151  
507  On July 2, a giant alien mothership enters orb...  6.794831  
30   Peter Parker is going through a major identity...  6.778496