In [35]:
## ! pip install scipy

import pandas as pd
import numpy as np
from scipy.sparse.linalg import svds


## 1. 데이터준비

In [2]:
rating_data = pd.read_csv('./ratings.csv')
movie_data = pd.read_csv('./movies.csv')

In [3]:
rating_data.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
movie_data.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

## 2. 전처리

### 피봇테이블 생성

In [5]:
df_user_movie_ratings = rating_data.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [6]:
df_user_movie_ratings.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     4.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  161084  161155  161594  161830  161918  161944  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  162376  162542  162672  163949  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 9066 columns]

### 피봇테이블 -> matrix 변환

In [7]:
import numpy as np
matrix = df_user_movie_ratings.values #numpy matrix로 만듦
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

### 사용자의 평균평점

In [8]:
user_ratings_mean = np.mean(matrix, axis = 1)
user_ratings_mean

array([0.00562541, 0.02923009, 0.02007501, 0.09783808, 0.04312817,
       0.01582837, 0.03364218, 0.04947055, 0.01864108, 0.01875138,
       0.01709685, 0.01853077, 0.02189499, 0.00650783, 0.49161703,
       0.01318112, 0.14990073, 0.01819987, 0.16490183, 0.03557247,
       0.06265167, 0.07947276, 0.29092213, 0.00849327, 0.00893448,
       0.06579528, 0.0097066 , 0.02360468, 0.00694904, 0.41986543,
       0.03171189, 0.01941319, 0.04985661, 0.08118244, 0.00529451,
       0.04147364, 0.01433929, 0.05255901, 0.02592102, 0.02139863,
       0.08487756, 0.03099493, 0.03639974, 0.00926539, 0.00838297,
       0.02128833, 0.01621443, 0.19887492, 0.03783366, 0.01665564,
       0.01356717, 0.02768586, 0.01411869, 0.01842047, 0.01522171,
       0.2081403 , 0.09121994, 0.02746525, 0.02652769, 0.02536951,
       0.05994926, 0.02360468, 0.04020516, 0.00926539, 0.01235385,
       0.02139863, 0.04268696, 0.04919479, 0.03695125, 0.03849548,
       0.01080962, 0.06833223, 0.59921685, 0.02217075, 0.05244

### matrix - user_ratings_mean

In [9]:
matrix_user_mean = matrix - user_ratings_mean.reshape(-1, 1)
matrix_user_mean

array([[-0.00562541, -0.00562541, -0.00562541, ..., -0.00562541,
        -0.00562541, -0.00562541],
       [-0.02923009, -0.02923009, -0.02923009, ..., -0.02923009,
        -0.02923009, -0.02923009],
       [-0.02007501, -0.02007501, -0.02007501, ..., -0.02007501,
        -0.02007501, -0.02007501],
       ...,
       [-0.01367748, -0.01367748, -0.01367748, ..., -0.01367748,
        -0.01367748, -0.01367748],
       [ 3.98698434, -0.01301566, -0.01301566, ..., -0.01301566,
        -0.01301566, -0.01301566],
       [ 4.95030885, -0.04969115, -0.04969115, ..., -0.04969115,
        -0.04969115, -0.04969115]])

In [10]:
pd.DataFrame(matrix_user_mean, columns = df_user_movie_ratings.columns).head()

movieId    1         2         3         4         5         6         7       \
0       -0.005625 -0.005625 -0.005625 -0.005625 -0.005625 -0.005625 -0.005625   
1       -0.029230 -0.029230 -0.029230 -0.029230 -0.029230 -0.029230 -0.029230   
2       -0.020075 -0.020075 -0.020075 -0.020075 -0.020075 -0.020075 -0.020075   
3       -0.097838 -0.097838 -0.097838 -0.097838 -0.097838 -0.097838 -0.097838   
4       -0.043128 -0.043128  3.956872 -0.043128 -0.043128 -0.043128 -0.043128   

movieId    8         9         10      ...    161084    161155    161594  \
0       -0.005625 -0.005625 -0.005625  ... -0.005625 -0.005625 -0.005625   
1       -0.029230 -0.029230  3.970770  ... -0.029230 -0.029230 -0.029230   
2       -0.020075 -0.020075 -0.020075  ... -0.020075 -0.020075 -0.020075   
3       -0.097838 -0.097838  3.902162  ... -0.097838 -0.097838 -0.097838   
4       -0.043128 -0.043128 -0.043128  ... -0.043128 -0.043128 -0.043128   

movieId    161830    161918    161944    162376    162542    162672    163949  
0       -0.005625 -0.005625 -0.005625 -0.005625 -0.005625 -0.005625 -0.005625  
1       -0.029230 -0.029230 -0.029230 -0.029230 -0.029230 -0.029230 -0.029230  
2       -0.020075 -0.020075 -0.020075 -0.020075 -0.020075 -0.020075 -0.020075  
3       -0.097838 -0.097838 -0.097838 -0.097838 -0.097838 -0.097838 -0.097838  
4       -0.043128 -0.043128 -0.043128 -0.043128 -0.043128 -0.043128 -0.043128  

[5 rows x 9066 columns]

## 3. 잠재요인기반 협업 필터링


### 행렬분해 : U 행렬, sigma 행렬, Vt 전치행렬 반환 (scipy의 svds사용)

In [16]:
U, sigma, Vt = svds(matrix_user_mean, k = 12)


In [17]:
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(671, 12)
(12,)
(12, 9066)


### 1차원행렬 -> 대칭행렬 (numpy의 diag사용)

In [18]:
sigma= np.diag(sigma)
sigma.shape

(12, 12)

In [20]:
sigma[0]

array([105.72437051,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ])

In [21]:
sigma[1]

array([  0.        , 110.15522471,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ])

### 원본행렬(R) 로 복구 (U,sigma,Vt 내적)

In [23]:
R = np.dot(np.dot(U, sigma), Vt)

In [24]:
R.shape

(671, 9066)

### matrix + user_ratings_mean

In [36]:
svd_user_predicted_ratings  = R + user_ratings_mean.reshape(-1, 1)

In [37]:
df_svd_preds = pd.DataFrame(svd_user_predicted_ratings, columns = df_user_movie_ratings.columns)
df_svd_preds.head()

movieId    1         2         3         4         5         6         7       \
0       -0.079686  0.021779 -0.013837 -0.005870 -0.028877  0.032371  0.000715   
1        1.428452  1.608841  0.529476  0.168278  0.520809  1.107473  0.529719   
2        0.977246  0.396971  0.000299  0.027444  0.021287  0.141458 -0.057134   
3        1.870844  1.169993  0.252202  0.094831 -0.181713 -0.511953 -0.027820   
4        1.182777  0.924903  0.075998  0.061505  0.602680 -0.159825  0.339925   

movieId    8         9         10      ...    161084    161155    161594  \
0       -0.004428 -0.005219  0.038195  ... -0.004324 -0.004352  0.010478   
1        0.089376  0.296270  1.970031  ...  0.013227 -0.002275  0.020680   
2        0.031633 -0.012538  0.383576  ...  0.002761  0.004907 -0.014190   
3       -0.143080  0.013247  1.461694  ...  0.026412 -0.027245  0.054681   
4        0.081534 -0.079666  0.535018  ... -0.029124 -0.029357  0.009064   

movieId    161830    161918    161944    162376    162542    162672    163949  
0       -0.004256 -0.003944 -0.005674  0.018157 -0.005575 -0.005297 -0.003766  
1       -0.005245 -0.007644 -0.021019  0.031243 -0.000957 -0.000753  0.026901  
2       -0.000251 -0.006007 -0.003189 -0.026916  0.014637  0.013287 -0.005741  
3        0.018450  0.034544 -0.035740  0.088889 -0.019365 -0.017113  0.066559  
4       -0.029092 -0.030890 -0.057453  0.026344 -0.024027 -0.024614 -0.032752  

[5 rows x 9066 columns]

In [39]:
df_svd_preds.shape

(671, 9066)

## 4. 영화추천 사용자함수

In [40]:
def recommend_movies(df_svd_preds, user_id, ori_movies_df, ori_ratings_df, num_recommendations=5):
    
    #현재는 index로 적용이 되어있으므로 user_id - 1을 해야함.
    user_row_number = user_id - 1 
    
    # 최종적으로 만든 pred_df에서 사용자 index에 따라 영화 데이터 정렬 -> 영화 평점이 높은 순으로 정렬 됌
    sorted_user_predictions = df_svd_preds.iloc[user_row_number].sort_values(ascending=False)
    
    # 원본 평점 데이터에서 user id에 해당하는 데이터를 뽑아낸다. 
    user_data = ori_ratings_df[ori_ratings_df.userId == user_id]
    
    # 위에서 뽑은 user_data와 원본 영화 데이터를 합친다. 
    user_history = user_data.merge(ori_movies_df, on = 'movieId').sort_values(['rating'], ascending=False)
    
    # 원본 영화 데이터에서 사용자가 본 영화 데이터를 제외한 데이터를 추출
    recommendations = ori_movies_df[~ori_movies_df['movieId'].isin(user_history['movieId'])]
    # 사용자의 영화 평점이 높은 순으로 정렬된 데이터와 위 recommendations을 합친다. 
    recommendations = recommendations.merge( pd.DataFrame(sorted_user_predictions).reset_index(), on = 'movieId')
    # 컬럼 이름 바꾸고 정렬해서 return
    recommendations = recommendations.rename(columns = {user_row_number: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num_recommendations, :]
                      

    return user_history, recommendations

In [42]:
already_rated, predictions = recommend_movies(df_svd_preds, 330, movie_data, rating_data, 10)

In [44]:
already_rated.head(10)

userId  movieId  rating  timestamp  \
47     330     1094     5.0  948577200   
14     330      213     5.0  948577039   
34     330      527     5.0  948577164   
45     330     1035     5.0  948574126   
48     330     1172     5.0  948575236   
53     330     1249     5.0  948576522   
27     330      373     5.0  948576522   
58     330     1428     5.0  948731410   
61     330     1575     5.0  948577442   
67     330     1683     5.0  948578017   

                                             title  \
47                         Crying Game, The (1992)   
14  Burnt by the Sun (Utomlyonnye solntsem) (1994)   
34                         Schindler's List (1993)   
45                      Sound of Music, The (1965)   
48  Cinema Paradiso (Nuovo cinema Paradiso) (1989)   
53                Femme Nikita, La (Nikita) (1990)   
27                            Red Rock West (1992)   
58                               Angel Baby (1995)   
61                                   Gabbeh (1996)   
67                   Wings of the Dove, The (1997)   

                           genres  
47         Drama|Romance|Thriller  
14                          Drama  
34                      Drama|War  
45                Musical|Romance  
48                          Drama  
53  Action|Crime|Romance|Thriller  
27                       Thriller  
58                          Drama  
61                          Drama  
67                  Drama|Romance

In [45]:
predictions

movieId                                      title  \
246      296                        Pulp Fiction (1994)   
294      356                        Forrest Gump (1994)   
497      608                               Fargo (1996)   
487      590                  Dances with Wolves (1990)   
316      380                           True Lies (1994)   
40        47                Seven (a.k.a. Se7en) (1995)   
313      377                               Speed (1994)   
214      260  Star Wars: Episode IV - A New Hope (1977)   
295      357         Four Weddings and a Funeral (1994)   
488      592                              Batman (1989)   

                                       genres  Predictions  
246               Comedy|Crime|Drama|Thriller     2.060064  
294                  Comedy|Drama|Romance|War     1.772814  
497               Comedy|Crime|Drama|Thriller     1.526111  
487                   Adventure|Drama|Western     1.508960  
316  Action|Adventure|Comedy|Romance|Thriller     1.276646  
40                           Mystery|Thriller     1.265219  
313                   Action|Romance|Thriller     1.142113  
214                   Action|Adventure|Sci-Fi     1.076539  
295                            Comedy|Romance     1.065911  
488                     Action|Crime|Thriller     1.048861